import React from 'react';

import Pic from '../../../images/stock_relaxation_misc/pexels-maria-gulyaeva-2562560.jpg';

const S2Contact = props => {
	return (
		<>
			{/* Section 3 */}
			<section className="relative py-0 bg-white lg:py-20">
				<div className="flex flex-col items-center justify-between p-0 mx-auto md:px-10 max-w-7xl xl:px-5 lg:flex-row">
					<div className="flex flex-col items-center w-full px-4 pt-5 pb-20 md:px-10 lg:pt-20 lg:flex-row">
						<div className="relative z-10 order-2 w-full max-w-md bg-cover lg:max-w-2xl lg:w-7/12 md:order-1">
							<div className="relative flex flex-col items-center justify-center w-full h-full lg:pr-10">
								<img src={Pic} className="shadow-2xl  rounded-xl" />
							</div>
						</div>
						<div className="relative z-10 order-1 w-full max-w-2xl mt-20 lg:mt-0 lg:w-5/12 md:order-2">
							<form 
                            className="relative z-10 flex flex-col items-start justify-start px-6 py-10 bg-white shadow-2xl md:p-10 rounded-xl"
                            name="ContactForm"
                            method="post"
                            action="/thanks"
                            data-netlify="true"
                            data-netlify-honeypot="bot-field"
                            >
                                        <input type="hidden" name="bot-field" />
        <input type="hidden" name="form-name" value="ContactForm" />
								<h4 className="w-full font-serif text-4xl font-medium leading-snug text-center">
									Let's Connect!
								</h4>
								<div className="relative w-full mt-6 space-y-8">
									<div className="relative">
										<label className="absolute px-2 ml-2 -mt-3 font-medium text-gray-600 bg-white">
											First Name*
										</label>
										<input
											type="text"
											className="block w-full px-4 py-4 mt-2 text-base placeholder-gray-400 bg-white border border-gray-300 rounded-full focus:outline-none focus:border-green-500"
											placeholder="Marissa"
                                            name="FirstName"
                                            id="firstName"
                                            required
										/>
									</div>
									<div className="relative">
										<label className="absolute px-2 ml-2 -mt-3 font-medium text-gray-600 bg-white">
											Last Name*
										</label>
										<input
											type="text"
											className="block w-full px-4 py-4 mt-2 text-base placeholder-gray-400 bg-white border border-gray-300 rounded-full focus:outline-none focus:border-green-500"
											placeholder="Matthews"
                                            name="LastName"
                                            id="lastName"
                                            required
										/>
									</div>
									<div className="relative">
										<label className="absolute px-2 ml-2 -mt-3 font-medium text-gray-600 bg-white">
											Email Address*
										</label>
										<input
											type="text"
											className="block w-full px-4 py-4 mt-2 text-base placeholder-gray-400 bg-white border border-gray-300 rounded-full focus:outline-none focus:border-green-500"
											placeholder="yourEmail@email.com"
                                            name="Email"
                                            id="email"
                                            required
										/>
									</div>
									<div className="relative">
										<label className="absolute px-2 ml-2 -mt-3 font-medium text-gray-600 bg-white">
											Phone
										</label>
										<input
											type="tel"
											className="block w-full px-4 py-4 mt-2 text-base placeholder-gray-400 bg-white border border-gray-300 rounded-full focus:outline-none focus:border-green-500"
											placeholder="Phone Number"
                                            name="Phone"
                                            id="phone"
										/>
									</div>
									<div className="relative">
										<button
											className="inline-block w-full px-5 py-4 text-xl font-medium text-center text-white transition duration-200 bg-green-500 rounded-full hover:bg-green-600 ease"
										>
											Submit
										</button>
									</div>
								</div>
							</form>
							<svg
								className="absolute top-0 z-0 w-32 h-32 -mt-12 -ml-12 text-green-200 fill-current left-2 md:left-0"
								viewBox="0 0 91 91"
								xmlns="http://www.w3.org/2000/svg"
							>
								<g
									stroke="none"
									strokeWidth={1}
									fillRule="evenodd"
								>
									<g fillRule="nonzero">
										<g>
											<g>
												<circle
													cx="3.261"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.445"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.445"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 12)">
												<circle
													cx="3.261"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.525"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.525"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 24)">
												<circle
													cx="3.261"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.605"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.605"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 36)">
												<circle
													cx="3.261"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.686"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.686"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 49)">
												<circle
													cx="3.261"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.767"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="2.767"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 61)">
												<circle
													cx="3.261"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.846"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="2.846"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 73)">
												<circle
													cx="3.261"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.926"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="2.926"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 85)">
												<circle
													cx="3.261"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.006"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.006"
													r="2.719"
												/>
											</g>
										</g>
									</g>
								</g>
							</svg>
							<svg
								className="absolute bottom-0 z-0 w-32 h-32 -mb-12 -mr-12 text-green-500 fill-current right-10 md:right-0"
								viewBox="0 0 91 91"
								xmlns="http://www.w3.org/2000/svg"
							>
								<g
									stroke="none"
									strokeWidth={1}
									fillRule="evenodd"
								>
									<g fillRule="nonzero">
										<g>
											<g>
												<circle
													cx="3.261"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.445"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.445"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.445"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 12)">
												<circle
													cx="3.261"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.525"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.525"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.525"
													r="2.719"
													className
												/>
											</g>
											<g transform="translate(0 24)">
												<circle
													cx="3.261"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.605"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.605"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.605"
													r="2.72"
													className
												/>
												<circle
													cx="87.514"
													cy="3.605"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 36)">
												<circle
													cx="3.261"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.686"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="3.686"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.686"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 49)">
												<circle
													cx="3.261"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.767"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="2.767"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="2.767"
													r="2.719"
													className
												/>
											</g>
											<g transform="translate(0 61)">
												<circle
													cx="3.261"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.846"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="75.479"
													cy="2.846"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="2.846"
													r="2.719"
													className
												/>
											</g>
											<g transform="translate(0 73)">
												<circle
													cx="3.261"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="2.926"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="2.926"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="2.926"
													r="2.72"
													className
												/>
												<circle
													cx="75.479"
													cy="2.926"
													r="2.72"
													className
												/>
												<circle
													cx="87.514"
													cy="2.926"
													r="2.719"
												/>
											</g>
											<g transform="translate(0 85)">
												<circle
													cx="3.261"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="15.296"
													cy="3.006"
													r="2.719"
												/>
												<circle
													cx="27.333"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="39.369"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="51.405"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="63.441"
													cy="3.006"
													r="2.72"
													className
												/>
												<circle
													cx="75.479"
													cy="3.006"
													r="2.72"
												/>
												<circle
													cx="87.514"
													cy="3.006"
													r="2.719"
												/>
											</g>
										</g>
									</g>
								</g>
							</svg>
						</div>
					</div>
				</div>
			</section>
		</>
	);
};

export default S2Contact;
